#!/bin/bash

# qumran api branch merge 

BranchList="
 tmp_f4_monitor
"
WS_BR=master


for T in ${BranchList}; do
    echo "Merge to branch -> ${T}"
    git co ${T}
    git rebase ${WS_BR}
    git push
done

git co ${WS_BR}
echo "Done, switch back to ${WS_BR}."

